// Auto-generated by benchmarks/train_mlp_key.py
// This file is only compiled when the "learned-key" feature is enabled.
// Run `python benchmarks/train_mlp_key.py --output crates/key-lime/src/mlp_weights.rs`
// to regenerate from trained data.

pub const HIDDEN_SIZE: usize = 48;
pub const NUM_CLASSES: usize = 24;

// Placeholder weights (identity-like initialization).
// Replace with trained values from train_mlp_key.py.

// Shape: 12x48 (input to hidden)
pub const W1: &[f32] = &[0.0; 576];

// Shape: 1x48 (hidden bias)
pub const B1: &[f32] = &[0.0; 48];

// Shape: 48x24 (hidden to output)
pub const W2: &[f32] = &[0.0; 1152];

// Shape: 1x24 (output bias)
pub const B2: &[f32] = &[0.0; 24];
