[package]
name = "trailmix"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
beat-salad = { path = "../beat-salad" }
key-lime = { path = "../key-lime" }
sampler-platter = { path = "../sampler-platter" }
serde.workspace = true

[dev-dependencies]
serde_json = "1"

[lints]
workspace = true
